config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions
root 'sessions#index'
post "sessions/new" ,to: 'sessions#create'
  resources :posts , only: [:new, :create, :index]
  match '/signout', to: 'sessions#destroy', via: :delete
  post "posts/new" ,to: 'posts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
   attr_accessor :signed_in
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :create_remember_token
  before_create :create_remember_token
  has_secure_password
  has_many :posts

  private

  def create_remember_token

  self.remember_token =  Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception
  include SessionsHelper


  def sign_in(user)

cookies.permanent[:remember_token] = user.remember_token

  end
  helper_method :sign_in

  def signed_in?

  cookies[:remember_token].empty? == false

  end
helper_method :signed_in?

def validate_user
 if cookies[:remember_token].empty? == true
     flash[:danger] = "please log in to post"
   redirect_to new_session_path
 end
end

  def current_user
   @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

   def sign_out
     cookies[:remember_token] = nil
     @current_user = nil
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :validate_user, only: [:new, :create]



def index

@posts = Post.all
end


def new


end

def create
 user = User.find_by(remember_token: cookies[:remember_token])
post  = User.new.posts.new(body:params[:post][:body])

 post.user_id = user.id
post.save
 if post.save
 redirect_to :root
else
  render 'root'
 end
end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  
  end

  def new

  end


  def create
    user = User.find_by(email: params[:session][:email])

      if user && user.authenticate(params[:session][:password])
        sign_in user
         flash[:success] = "You have been sucessfully signed in"
       redirect_to :root
     else
        flash[:danger] = "Invalid email/password combination"
       render 'new'
      end
  end

  def show

  end

def destroy
  current_user
     sign_out
     flash[:danger] = "User has been signed out"
     redirect_to :root
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <div class="container">
     <% flash.each do |key, value| %>
       <div class="alert alert-<%= key %>"><%= value %></div>
     <% end %>
    <%= yield %>

      <%#= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/posts/index.html.erb
<p>yes i am the great almight post index view</p>



<% @posts.each do |p| %>
<%if signed_in?%>
 <%=p.user.name%>
<%=p.body%> <br>
 <% elsif !signed_in? %>
<%=p.body%> <br>
<% end %>
<% end %>

<br>




<%if signed_in?%>
<%= link_to 'New post', new_post_path %>
<%= link_to 'Sign out', signout_path, method: :delete,data: { confirm: 'Are you sure?' } %>

<% else %>
<%= link_to 'Sign in', new_session_path %>
<% end %>

app/views/posts/new.html.erb
<p>New post</p>

<%= form_for(:post, url:new_post_path)do |f| %>
<p>
<%= f.label :body, "Your Post" %><br/>
<%= f.text_area :body %>
</p>
<p>
<%= f.submit 'Submit'%>
</p>
<% end %>